### ISSUE TITLE
Identity Hub: CredentialsVerifier failures on invalid Verifiable Credentials

### ISSUE THREAD

**Issue by marcgs** [agera-edc/IdentityHub#47]
Feature #13

## Description

IdentityHubCredentialsVerifier needs to return a failure in case an invalid Verifiable Credential is found. The current implementation filters out Verifiable Credentials with invalid claims or signature, and a warning is logged. This behaviour must be changed to return a failed Result and thus be able to detect this situation quickly.

## Acceptance Criteria
- [ ] IdentityHubCredentialsVerifier returns failure if invalid VCs are found

**Comment by paullatzelsperger** [comment]
@marcgs @ouphi is this closed by #24?

**Comment by marcgs** [comment]
@paullatzelsperger indeed closed by https://github.com/eclipse-dataspaceconnector/IdentityHub/pull/24. Closing story.
